### ISSUE TITLE
Reading BP2004 data

### ISSUE THREAD

**Issue by ar4** [Statoil/SegyIO#108]
I tried using SegyIO to read the first BP2004 data segy file (http://s3.amazonaws.com/open.source.geoscience/open_data/bpvelanal2004/shots0001_0200.segy.gz), but it did not appear to work correctly.

After `gunzip`ing:

`f=segyio.open('shots0001_0200.segy')`
`f.ilines` and `f.xlines` only show one inline and one crossline.

I tried running the `copy-sub-cube.py` example. Even though this is 2D data, I thought this would still extract 5 traces. It ran, without errors, but when checking the file using the SU command segyread, I get the errors:

> segyread: discrepant tr.ns = 2001 with tape/user ns = 50
> 	... first noted on trace 1
> 
> segyread: discrepancy found in header and trace ns values
> the value (50) was used to extract traces

so it seems that the headers were not set correctly. It also reports that there is only 1 trace in the file.

**Comment by jokva** [comment]
I'll have a look at the file right away, and see if I can figure out what's going on.

**Comment by jokva** [comment]
I've poked a bit around now. We too find 2001 samples per trace, but find 240200 traces in the file. It appears not to have any reasonable geometry set (all the inline header words, byte 189, are set to 0). The name, too, indicates that it's sorted on shots, meaning inline/xline support is meaningless.

Data organised on shots like this enjoy no extra syntactic support from segyio, other than giving (easy) access to individual and ranges of traces, and their headers.

```
In [21]: f.tracecount
Out[21]: 240200`

In [22]: f.samples
Out[22]: array([  0.00000000e+00,   6.00000000e+00,   1.20000000e+01, ...,
         1.19880000e+04,   1.19940000e+04,   1.20000000e+04], dtype=float32)

In [31]: f.attributes(segyio.TraceField.SourceX)[:]
Out[31]: array([   500,    500,    500, ..., 100000, 100000, 100000], dtype=int32)
```

**Comment by ar4** [comment]
Ah, I see. Thank you.

**Comment by jokva** [comment]
I'm not sure if this addresses your problems at all @ar4. Are these files supposed to be processed, post-stack volumes?

**Comment by ar4** [comment]
No, it is, as you noticed, shot gathers. I hoped that SegyIO might provide an easy way of reading shot gathers. It seems that it is not really designed for that purpose.

**Comment by jokva** [comment]
Shot gathers might be in the pipeline (I can have a look), and feedback and testing would be very welcome.

If it's sufficient to map traces to their source X/Y or some other identifier that's pretty straight forward in segyio and I'd be happy to either help you along or implement it.

**Comment by ar4** [comment]
I haven't yet found a good open source library for reading shot gathers efficiently, but I am continuing to look.

I am not sure that the current design of SegyIO suits the problem, though. Applications that access shot gathers often run in parallel on many nodes. Adding parallel i/o would probably make the library quite a bit more complicated.

**Comment by jokva** [comment]
It probably would do, yes. Parallel *reading* via multiple file handles isn't so bad, especially with memory mapping, but if you need to synchronise writes complexity quickly becomes an issue.

Anyway, if I get this right, you can read all traces that matches some source X. It's a little bit clunky now, but if this works for you I'd be happy to look into better library support for it:

```
In [34]: numpy.where(f.attributes(segyio.TraceField.SourceX)[:] == 500)
Out[34]: (array([   0,    1,    2, ..., 1198, 1199, 1200]),)

In [35]: srcx = numpy.where(f.attributes(segyio.TraceField.SourceX)[:] == 500)[0]

In [36]: segyio.tools.collect(f.trace[srcx[0]:srcx[-1]+1])
Out[36]: 
array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.39914865e-03,  -4.38692048e-04,  -4.88635898e-03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
         -2.85512535e-03,  -5.90696931e-03,  -8.52246070e-04],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
         -6.01528957e-03,   1.45460083e-03,   5.36009297e-03],
       ..., 
       [  0.00000000e+00,   1.12675785e-04,   7.61029124e-03, ...,
         -4.81747789e-04,   8.09508376e-04,   1.31214899e-03],
       [  0.00000000e+00,   1.20038092e-02,   2.42672145e-01, ...,
         -4.36878297e-04,   1.33387232e-03,   1.64548401e-03],
       [  0.00000000e+00,   5.65216132e-02,   7.81455278e-01, ...,
          4.47050203e-04,   2.01990362e-03,   8.74300487e-04]], dtype=float32)

```

**Comment by ar4** [comment]
That is exactly the sort of thing I want to do, thank you. For it to be efficient, however, I imagine a few changes are necessary. The problems I see at the moment are:
* Opening a file seems to involves scanning the headers of the whole file. This would be problematic if the file were opened on many nodes simultaneously.
* Even on files like the BP2004 one, which is very small, searching through the headers to find the traces with the right source coordinates is slow.

Both of these could potentially be solved by splitting the opening process into two stages. The first is the creation of a type of database file, which stores information about the file. If users are required to say how they wish to index the file when performing this step (such as reading shot gathers), then the database could include the appropriate trace indices (the first and last trace indices for each shot, if the file appears to be already sorted into shot gathers). Then in the second stage of opening, only this database file needs to be read. When a user is going to open the file on many nodes, they could run the first stage on a single node, and then the second stage on all of the nodes.

**Comment by jokva** [comment]
> That is exactly the sort of thing I want to do, thank you

Splendid!

> Opening a file seems to involves scanning the headers of the whole file. This would be problematic if the file were opened on many nodes simultaneously.

Sure, but the files can be memory mapped (on POSIX systems).

```
>>> f.open('file.sgy')
>>> f.mmap()
True
```

Which should reduce the load significantly. However, opening a file does *not* scan all the headers (it checks the binary header, of course, and a couple of trace headers, and is quite cheap.).

> Even on files like the BP2004 one, which is very small, searching through the headers to find the traces with the right source coordinates is slow.

Probably, but try with memory mapping and the `attributes` feature (which exists exactly for this use case). If you have specific test cases here we'd love to hear about them so we can address performance issues.

As for the splitting procedure for distributing work, that's a very interesting idea and something I'd love to see in tools or something. It sounds pretty useful and quite easy to implement too.

**Comment by ar4** [comment]
When you say "a couple of trace headers", do you mean a couple of headers (inline number, xline number, ...) for every trace? Opening that small BP file takes non-negligible time for me, so you can imagine how long it would take to open a recent dataset, with hundreds of GB in each file. (And memory mapping such files probably wouldn't work very well either.) Since some of the headers that it is reading (inline, xline) are not even what I am usually interested in, this is an unpleasant waste. There doesn't currently seem to be any parameter for altering the behaviour when opening a file.

**Comment by jokva** [comment]
I take it back, we actually scan through all the headers (*if* a file appears to be a proper cube, i.e. with correct iline/xline for every trace). I see now that it can be optimised a bit too, which I'll get back to in a couple of weeks, I have two conferences coming up).

I can add a parameter to open() that *forces* segyio not to bother with figuring out geometry for your use case, which hopefully speeds up a bit. That's a quick fix.

**Comment by ar4** [comment]
I'll stop taking your time now, so that you can focus on the conferences ;). Just to check, will the new parameter mean that open is almost free - doesn't check any traces at all. Then I simply have the option to step through the traces, reading the headers and samples one at a time? Presumably it will then also need to check to make sure that I have not reached the end of the file. That sounds like it is what I need for now, although I do worry that it might be so far from what was intended with segyio that it might be quite an inelegant addition.

**Comment by jokva** [comment]
There we go: https://github.com/Statoil/SegyIO/pull/110 I'll try and get someone to look at it soon, but feel free to apply the patch yourself and try it out.


To answer your question, **yes**, open should be virtually free. It reads the binary header and a little bit more, plus some size data to figure out how many traces there are. This comes with a restriction, though, there's a *fundamental* assumption that all traces are of the same length. The spec surely allows traces to vary in length, but we've chosen to completely ignore that set of files.

I think we're still within the scope of segyio, so I wouldn't worry too much about that.
