### ISSUE TITLE
error after installing with pip

### ISSUE THREAD

**Issue by ar4** [Statoil/SegyIO#112]
I saw that there was a SegyIO package available on PyPI. I tried installing it using `pip install segyio`. There was of course no reason to believe that it should work, since the README describes another installation method, but I tried anyway. Installation seemed to be successful, however when I try to import the installed package, I get the error:

```
import segyio
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-fd810101fe07> in <module>()
----> 1 import segyio

/home/alanr/anaconda3/lib/python3.5/site-packages/segyio/__init__.py in <module>()
     80 from .open import open
     81 from .create import create
---> 82 from .segy import SegyFile, spec

/home/alanr/anaconda3/lib/python3.5/site-packages/segyio/segy.py in <module>()
     22 from segyio._trace import Trace
     23 from segyio._field import Field
---> 24 import segyio._segyio as _segyio
     25 
     26 from segyio.tracesortingformat import TraceSortingFormat

ImportError: /home/alanr/anaconda3/lib/python3.5/site-packages/segyio/_segyio.cpython-35m-i386-linux-gnu.so: undefined symbol: PyInt_AsSsize_t
```

Is the `pip install` approach simply not supported for SegyIO? Since it is a very common method of installing python packages, it might be worth mentioning this in the README.

My details:
```
compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux
release    : 4.4.0-67-generic
machine    : i686
processor  : i686
CPU cores  : 2
interpreter: 32bit
CPython 3.5.2
IPython 4.2.0
```

**Comment by pgdr** [comment]
I'm not sure we've testet `pip install` with Python 3, but it should work for Python 2.7.  I'll leave it to @jokva to answer for pip and Python 3.  Perhaps the offending line should simply be replaced with `PyLong_AsSsize_t`?

**Comment by jokva** [comment]
We haven't god good testing on the pip package, and there's probably some bug there. I'll have a look and fix it on Friday.

The PyInt_AsSize thing is a python2/3 compatibility thing though and makes me think we have some slightly unportable code in the bindings.

**Comment by ar4** [comment]
Perhaps you just need to push a new release to PyPI, as the one currently there is quite old (October 2016). Have you considered setting-up automatic deployment to PyPI from Travis when all tests pass?

**Comment by pgdr** [comment]
Yes, we have actually discussed automatic build (if not deploy) a pip package in our nightly testing scripts.  However, as we don't primarily use pip internally in Statoil, this has gotten less priority.

You are right, though, that we should at least push a new version now.

**Comment by jepebe** [comment]
I have updated the PyPi package so it should work now. Please let us now if you have any more issues.

**Comment by ar4** [comment]
I confirm that it does work now. Many thanks!

**Comment by pgdr** [comment]
Great, thanks for the issue and testing!
