### ISSUE TITLE
Access trace using a trace index value from an array

### ISSUE THREAD

**Issue by ar4** [Statoil/SegyIO#113]
A short example, where `segy` is of `SegyFile` class, opened with `segyio.open()`:

```
a = np.array([0])
s.trace[0] # works
s.trace[a[0]] # fails
```
An ugly workaround is `eval(s.trace[%d] % a[0])`.

**Comment by ar4** [comment]
Oops, the problem was actually that a[0] is a float.

**Comment by pgdr** [comment]
Hi, thanks for the report.  We'll have a look at it.

It's strange, because `isinstance(a[0], int)` will be `True`.

**Comment by jokva** [comment]
Hi @ar4 

I think https://github.com/Statoil/SegyIO/pull/114 should solve most of these problems.

**Comment by ar4** [comment]
Excellent. Many thanks!
