### ISSUE TITLE
Large Files and Remap Trace Header Questions

### ISSUE THREAD

**Issue by induswell** [Statoil/SegyIO#132]
Hello All:

I'm working with large prestack 3D SEG-Y files (>1TB) that have a few non-standard trace header mappings, ie: the inlines and crosslines are stored in different byte locations.  I have a couple of newbie questions:

1. What is the best way to open a large SEG-Y file and traverse trace by trace?
2. How would I remap some trace headers to different byte locations?

I appreciate your help.

Thanks!

**Comment by jokva** [comment]
The best way if you have many traces is to read the file trace-by-trace, or, if you choose to program the logic, some chunks-by-chunks, and *not* mmap the file. If you read ranges of traces (by using the `f.trace[begin:end]` notation) you will be given a generator, so it doesn't use much memory.

You can opt to partition the file by yourself by reading it with `f.trace.raw[begin:end]` in smaller chunks. This might not be worth the effort, depending on what you're doing.

The `segyio.open` function takes two parameters, `iline` and `xline` which can be used to specify non-standard byte headers. `segyio.open('file.sgy', iline = iline_byte, xline = xline_byte)` should do what you want.

We do appreciate feedback, so if something seems to work a bit odd then please let us know, and thanks for using segyio.

**Comment by jokva** [comment]
One constraint is that these alternative byte locations *must* align with some other byte location from the specification. Inline is 189 according to the spec, but putting the number at 190 would be a violation, but 193 is fine.

**Comment by induswell** [comment]
Thank you very much, @jokva. I will try using your suggestions.

**Comment by jokva** [comment]
Please let us know how it works - if there's a problem we (probably) want to fix it.

**Comment by jokva** [comment]
Since this seems to be resolved I'm closing the issue now. Please feel welcome to open new issues if you have more questions, suggestions, or problems.
