### ISSUE TITLE
Missing lib after pip install

### ISSUE THREAD

**Issue by kwinkunks** [Statoil/segyio#199]
Installed v1.3.8 with pip, seemed to install no problem. (Tried Python 3.6 and Python 3.5 [both Anaconda], on MacOS)

However, `import segyio` gives me

    ImportError: dlopen(/Users/matt/anaconda/envs/python3/lib/python3.5/site-packages/segyio/_segyio.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libsegyio.1.dylib
      Referenced from: /Users/matt/anaconda/envs/python3/lib/python3.5/site-packages/segyio/_segyio.cpython-35m-darwin.so
      Reason: image not found

See below for more. 

Seems similar to #112.

![image](https://user-images.githubusercontent.com/1692372/34493647-39808c68-efc3-11e7-8f84-9c9580711b5b.png)

**Comment by kwinkunks** [comment]
Quick update, just FYI: I installed from source and am up and running again.

**Comment by jokva** [comment]
Hi,

Was this with a pre-built wheel?

**Comment by kwinkunks** [comment]
The `pip install` was from PyPi. The install from source was from the current git `master`. Does that answer your question?

**Comment by jokva** [comment]
Yes, that means you used a pre-built wheel (with 99% certainty). I'll review the OS X packaging and make sure it properly bundles the core lib.

**Comment by jokva** [comment]
I just read through the build-and-dist-logs, and you're right, it doesn't properly bundle the core lib. I'm working on a fix now.

**Comment by jokva** [comment]
Alright, I think #200 should fix your problem. I'll make a preview release of that particular commit, which we can use to test binary installs.

**Comment by jokva** [comment]
Hi Matt @kwinkunks 

Could you please try `pip install segyio==1.4.b3`?

**Comment by kwinkunks** [comment]
Hey, sorry for the slowness... It worked — installed no trouble in my Python 3.6 conda env. Thanks!

**Comment by jokva** [comment]
No problem at all. Happy it worked! I'll merge the fix and close the issue, and possibly release a bugfix version for 1.3.8.

We're anticipating 1.4 soon-ish (maybe a week or two).

Please don't hesitate to make more issues if you have problems or suggestions for improvements.
