### ISSUE TITLE
Install Error: Fetal error LNK 1181.

### ISSUE THREAD

**Issue by dylanocean** [Statoil/segyio#211]
Anyone has problems with installing the package? I got the fetal error LNK 1181 in CMD window. I'm new with python. Thank you so much.

**Comment by jokva** [comment]
What is your pip version?

`python -m pip --version`

**Comment by jokva** [comment]
Immediately, my theory is that you pull the source package, and not the pre-built binary package. Pip versions that are too old won't pick up the binary package, so it might need some forcing or upgrading.

You can also try `pip install --only-binary :all:`

**Comment by dylanocean** [comment]
Thank you! Problem solved!

**Comment by dylanocean** [comment]
But I found the version is 1.3.3 and cannot use 1.3.8.

**Comment by jokva** [comment]
I'll have a look at that - 1.3.9 should've been made available for Windows and macOS too, but it seems they're not.

**Comment by jokva** [comment]
You're right, something's wrong in the powershell code that checks if wheels should be uploaded or not. I'll have a look at it in the morning.

**Comment by jokva** [comment]
I've fixed this now, and uploaded new images for 1.3.9

https://pypi.org/project/SegyIO/1.3.9/

Please reopen this issue, or create a new one, if they don't work for you.

Thanks for using segyio!
