### ISSUE TITLE
How to show the segy data?

### ISSUE THREAD

**Issue by swpucl** [Statoil/segyio#218]

**Comment by pgdr** [comment]
Do you want to plot, or do you want to see the actual textual data?

If you want to plot it, take a look at [Segyviewer](https://github.com/Statoil/segyviewer).

`pip install segyviewer`
and then
`segyviewer <file.segy>`

**Comment by jokva** [comment]
@pgdr's answer's right on the money, you need a separate application like segyviewer if you want to plot it.

**Comment by jokva** [comment]
Other than that, we support any textual representation of data that numpy support.

**Comment by swpucl** [comment]
@pgdr thanks your answer. I install segyviewer, but show typeError: 'module' object is not callable.

**Comment by swpucl** [comment]
@jokva the segyviewer  need PyQt4 support?

**Comment by jokva** [comment]
Yes, you need PyQt4 for it.

**Comment by jokva** [comment]
Since there hasn't been any activity for a while. If your issues aren't resolved, please re-open or create a new issue.
