### ISSUE TITLE
return type should not be int -- numpy.ndarray instead?

### ISSUE THREAD

**Issue by tavin** [Statoil/segyio#222]
https://github.com/Statoil/segyio/blob/ee0bd31975354c8130f107d259e07725bf916cd3/python/segyio/segy.py#L193

**Comment by jokva** [comment]
You're absolutely right - pre-release this used to be an int, and the documentation has not been updated.

**Comment by jokva** [comment]
https://github.com/Statoil/segyio/commit/5957ce7810e3866dceb9bbbc19fe8943ef27800f fixes this. Thanks for the report!
