### ISSUE TITLE
segy file from scratch, segy compliance

### ISSUE THREAD

**Issue by OlivierMorere** [Statoil/segyio#232]
The following code creates a small segy file that can be properly opened and viewed with segyviewer.
However, impossible to open it with OpendTect 6.0.0 (application crash at segy import).
How do you make sure created files are segy compliant ?

```
segyoutpath = './test.segy'
spec = segyio.spec()
spec.sorting = 2
spec.format = 1
spec.samples = list(range(30))
spec.ilines = list(range(10))
spec.xlines = list(range(20))

with segyio.create(segyoutpath, spec) as f:
    # write the line itself to the file and the inline number in all this line's headers
    for ilno in spec.ilines:
        f.iline[ilno] = np.zeros(
            (len(spec.xlines), len(spec.samples)), dtype=np.single) + ilno
        f.header.iline[ilno] = {
            segyio.TraceField.INLINE_3D: ilno,
            segyio.TraceField.offset: 0
        }
    # then do the same for xlines
    for xlno in spec.xlines:
        f.header.xline[xlno] = {
            segyio.TraceField.CROSSLINE_3D: xlno,
            segyio.TraceField.TRACE_SAMPLE_INTERVAL: 4000
    }
```

Tested on f607169c981cc23723d12451bfdf7e58fcac0823

**Comment by jokva** [comment]
Compliancy with the full specification is a user responsibility, as there are *way* too many configurable things for the library to make up any sort of reasonable default.

To make it compliant and/or openable with OpendTect you need to figure out what fields it requires. segyio only writes a couple of fields for you (and only in the binary header), so your program has the right idea.

**Comment by jokva** [comment]
http://doc.opendtect.org/5.0.0/doc/od_userdoc/content/app_c/app_c.htm#examine_scan

The first thing that comes to mind is CDP-X/Y not being set, although it shouldn't crash on such an error.

**Comment by jokva** [comment]
Hi, Olivier, and sorry for not getting back to you sooner.

I just compiled OpendText 6.0.0 and it opened the file created by your test program loads just fine. Have you tried any more to get this to work?

**Comment by jokva** [comment]
I'll close this issue now, assuming you've figured it out. Please do not hesitate to re-open this issue or create a new one if you have more information, or any other questions or requests.
