### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by srib** [Statoil/segyio#237]
Given that the library is already well documented, I think it is a good idea to host online documentation for the library.

I can contribute a PR if there is interest.

**Comment by jokva** [comment]
I 100% agree, and I actually had this discussion with a friend and colleague earlier today. Something like readthedocs or travis-provided upload to somewhere would be a good start.

Do you have a preference or idea on how/where?

**Comment by srib** [comment]
I'd recommend readthedocs. They have good support for the open source community.

**Comment by jokva** [comment]
I guess that's pretty easily integrated into our CI+deploy pipeline.

**Comment by AdmcCarthy** [comment]
Yes, this would be good! If you get this going I could help if you would like to expand any tutorials/getting started?

**Comment by jokva** [comment]
I've started, actually, but it's evident from the rendering that our documentation needs some work. http://segyio.readthedocs.io/en/latest/

I need to properly create a makefile and clean up the docstrings to match numpy conventions (with test-rendering at readthedocs), but it's a reasonable starting point I think. Any contribution to cleaning up docstrings is obviously very welcome - I personally will work on this sometime next week.

**Comment by jokva** [comment]
As mentioned, I've started this work. I've been using the doc branch as my playground https://github.com/Statoil/segyio/tree/doc 

What's currently lacking is:

* A few classes and types haven't had a docstring revision (to numpy style)
* The index still needs some work
* Hyperlinking and table-of-contents aren't complete
* Makefile entry

Other than it's shaping up. Any help is obviously very much appreciated. For the current revision, see http://segyio.readthedocs.io/en/latest/index.html

**Comment by jokva** [comment]
Thanks for the issue! I've merged https://github.com/Statoil/segyio/pull/244 now, and the build hook should work.

https://segyio.readthedocs.io/

I hope that the documentation will receive a lot of love in the future.

**Comment by srib** [comment]
Sweet, thanks for this! 👍
