### ISSUE TITLE
bug in segyio-crop?

### ISSUE THREAD

**Issue by MathiasAlerini** [Statoil/segyio#247]
It seems segyio-crop does not update the trace header field 115 (ns/TRACE_SAMPLE_COUNT) after cropping the number of samples.

**Comment by jokva** [comment]
I can confirm it does not.

https://github.com/Statoil/segyio/blob/751eda6188197d3cc00366c7dab8ed334930b438//applications/segyio-crop.c#L434

Delay recording time is the only trace header field that's updated, but it's an easy fix. Hang on, I'll make a patch.

**Comment by jokva** [comment]
https://github.com/Statoil/segyio/pull/248 should fix this bug.

**Comment by jokva** [comment]
I'll see if I can make a (comfortable) test for it.

**Comment by jokva** [comment]
Fixed in #248
