### ISSUE TITLE
reference to trace content for SegyFile.trace

### ISSUE THREAD

**Issue by MathiasAlerini** [Statoil/segyio#255]
if doing 
f=seygio.open(filename)
f.trace is a numpy array. It would be good to use it as a reference to the content of the traces, so that we could for exemple update traces values with

```python
with segyio.open(filename) as f:
    f.trace = my_new_values
```

**Comment by jokva** [comment]
Probable solution: on `next()`, check if buffer is dirty and flush to disk.

**Comment by jokva** [comment]
Problem is last trace, so verify stopiteration is always raised and use that.

**Comment by jokva** [comment]
https://github.com/Statoil/segyio/pull/260 implements this feature.
