### ISSUE TITLE
Reading files from Cloud S3/ GCS

### ISSUE THREAD

**Issue by benaichouchem** [Statoil/segyio#261]
I am trying this library from a Cloud Jupyter notebook, and would like to read my seismic from S3/GCS, is there any plan to add this support?

**Comment by jokva** [comment]
Can't you copy to a local file from S3/GCS?

**Comment by jokva** [comment]
I'll have a look at available functionality and see how it works.

**Comment by benaichouchem** [comment]
I thought about copying the file to the local VM; but I am not sure if this is a great idea. If you have big files and have to download them locally every time. 

Let me know if you need hands implementing this, I would be happy to help.

**Comment by jokva** [comment]
Copying to the local VM will always work (because we rely on libc's `fopen`), but maybe there's something in GCS/S3 that makes this problem go away.

I haven't had the time to look into this, but if you know of a solution or a fix I'd be happy to include it.

**Comment by jokva** [comment]
I haven't found any reasonable way of accessing s3/gsc as regular files, and at the end of the day you need to download  the data to your local node anyway. If you have a way of doing this, I'd be very happy, but it looks like it would require segyio to do some heavy lifting, which isn't (currently) in the project's scope.

**Comment by jokva** [comment]
Alright, so I recommend accessing S3 files with a FUSE implementation https://github.com/s3fs-fuse/s3fs-fuse

FUSE would expose S3 files as if they were local files, and so segyio should work as expected.

Please try this out and see if it works for you, or if some new issues arise. After a bit of time, I will close this issue.

**Comment by jokva** [comment]
There won't be any native support for this in segyio - rather, use FUSE, s3fs, or otherwise fix this at the environment level (which will then work with _all_ programs, not just segyio).
