### ISSUE TITLE
EBCDIC example from doc not working

### ISSUE THREAD

**Issue by JesperDramsch** [Statoil/segyio#265]
The example to read the EBCDIC header throws a TypeError in my case.

```
>>> # using zip, from the zip documentation
>>> text = f.text[0]
>>> lines = map(''.join, zip( *[iter(text)] * 80))
>>> for line in lines:
...     print(line)
```
Gives an error in my case. `text = f.text[0]` gives a bytearray and needs to be changed to `text = f.text[0].decode("utf-8")` to work.

**Comment by jokva** [comment]
Good catch! You can also do `str` on it. It used to be more str-like, before being moved to a bytestr. The documentation needs an update

The entire text mechanic is pretty weak, and is a candidate for improvements in a potential segyio2. https://github.com/Statoil/segyio/blob/master/breaking-changes.md

We might actually do an improved text header thing and make it compatible, but the text headers tend to be the least interesting thing in a file, and consequently it has not received much love.

I'll fix the documentation right away, and maybe even review the behaviour w.r.t. byte arrays.

**Comment by jokva** [comment]
https://github.com/Statoil/segyio/commit/2b89ecedd81133338d907ca9ad20bf1dc4fee26c

`.decode` works only in python3, but `str` should work as expected in both 2 and 3.

**Comment by jokva** [comment]
Fixed upstream. Thanks!
