### ISSUE TITLE
好像不支持中文路径

### ISSUE THREAD

**Issue by lixiandea** [Statoil/segyio#266]
我使用的python3.6版本，按理来说不是python的问题，但是使用segyio打开对应的地质文件出现了问题。

**Comment by flikka** [comment]
这可能不是 @jokva 的意图

**Comment by jokva** [comment]
你收到错误信息吗？

**Comment by joakim-hove** [comment]
This is hysterical!

**Comment by lixiandea** [comment]
OSERROR : invalid argument

![default](https://user-images.githubusercontent.com/26404619/42988912-e18b134c-8c30-11e8-9c4c-cf17735257d7.png)

when I changed the name to english,it goes well

**Comment by jokva** [comment]
I created a file with a Chinese name, and it worked nicely here. Can you try change the `str(filename)` from trace traceback to `bytes(filename)`, and see if it works? It is C's `fopen` function that fails, and that just follows your operating system rules, but maybe the name gets corrupted from string conversion.

**Comment by lixiandea** [comment]
没用，emmm，有的时候会出现找不到文件的错误，你能和我说一下你的python版本和系统吗，我的python3.6.5+ windos7 不行，还有win10也是不行

**Comment by jokva** [comment]
```
$ cp segyio/test-data/small.sgy 小文件.sgy
$ python2 -c "import sys, segyio; print(sys.version); print(segyio.open('小文件.sgy').ilines)"
2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]
[1 2 3 4 5]
$ python3 -c "import sys, segyio; print(sys.version); print(segyio.open('小文件.sgy').ilines)"
3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
[1 2 3 4 5]
```

On Debian Stretch. Same results on RHEL7.

**Comment by jokva** [comment]
https://github.com/Statoil/segyio/pull/268 

If you want, you can try this.

**Comment by lixiandea** [comment]
ok,thanks a lot
