### ISSUE TITLE
Inference of geometry failing.

### ISSUE THREAD

**Issue by JesperDramsch** [Statoil/segyio#267]
Hi,

I looked at the docs, where it said, that Xline is necessary for inference of geometries. These are the remappings, Iline and Xline are in line with Segy Rev1, which is also reflected in the image. Segyio finds the correct headers, as you can see in the minimal example.

> C31------------------------TRACE HEADERS (BYTES)--------------------------------
> C32BIN COORD_X(MT)....(181-184)     BIN COORD_Y(MT)..........(185-188)          
> C33INLINE.............(189-192)     CROSSLINE................(193-196)          

I prepared a minimal example here:

![segyio_issue](https://user-images.githubusercontent.com/2620316/42945886-dcf3a2e4-8b69-11e8-963e-01dd05f59096.PNG)

**Comment by jokva** [comment]
What does `old_segy.attributes(INLINE_3D)[:50]` print? And the same for xline.

**Comment by JesperDramsch** [comment]
> NameError: name 'INLINE_3D' is not defined

**Comment by jokva** [comment]
Sorry, I abbreviated, use `189` or `segyio.TraceField.INLINE_3D`.

**Comment by JesperDramsch** [comment]
It prints a list of the last 50 inline / xline values as I would expect.

**Comment by JesperDramsch** [comment]
For 20 values I get:

> [5036 5037 5038 5038 5038 5038 5038 5039 5039 5039 5039 5039 5040 5040 5040 5040 5040 5040 5040 5040]

> [10858 10858 10856 10857 10858 10859 10860 10856 10857 10858 10859 10860 10854 10855 10856 10857 10858 10859 10860 10861]

**Comment by jokva** [comment]
This is interesting - notice how your numbers are irregular? segyio expects that volumes are neatly ordered, i.e. they should be [N+0, N+1, N+2 ...] by [M, M, M, ...]. Assuming you have exactly one trace per inline/crossline combination you can maybe assemble a cube, but segyio has given up.

This is a speed tradeoff, because this assumption allows random access without an index. If the file is a proper volume it can be reorganised to meet segyio's assumptions.

**Comment by JesperDramsch** [comment]
I see. It's due to the cube being rotated I believe. Is there an easy fix for it?

**Comment by jokva** [comment]
Without physically changing the file? No. If that's acceptable, it's not so hard.

**Comment by JesperDramsch** [comment]
I'm fine with changing the file. Just trying to somehow get my seismic files into python in a sensible way.

Maybe a stupid suggestion for v2, would a "unsorted=True" flag work to bypass the assumption and lose some speed, but get the inference going?

**Comment by jokva** [comment]
That requires some substantial changes, but it's certainly possible.

**Comment by jokva** [comment]
I'll try to sketch out a code example soon.

**Comment by jokva** [comment]
```
#! /usr/bin/env python3

import sys
import numpy as np
import segyio

with segyio.open(sys.argv[1], ignore_geometry = True) as src: 

    ils = src.attributes(segyio.su.iline)[:]
    xls = src.attributes(segyio.su.xline)[:]

    inlines = np.unique(ils)
    crosslines = np.unique(xls)

    spec = segyio.tools.metadata(src)
    spec.ilines = inlines
    spec.xlines = crosslines
    spec.offsets = [1]

    if len(inlines) * len(crosslines) != len(src.trace):
        raise AssertionError("cube has missing traces")

    # map the label of each in/crossline to its position
    il_order = { k: i for i, k in enumerate(inlines) }
    xl_order = { k: i for i, k in enumerate(crosslines ) }

    stride = len(spec.xlines)

    intersects = zip(ils, xls) 
    with segyio.create(sys.argv[2], spec) as dst: 
        z = zip(src.trace[:], src.header[:], ils, xls, range(len(src.trace)))                                                                                                                                                                                                                                                  
        for trace, header, il, xl, j in z:
            i = il_order[il] * stride + xl_order[xl]
            dst.trace[i] = trace
            dst.header[i] = header

            if i != j: print("remapping {} -> {}".format(j, i))
```

This might work, or at least give you a general idea.

**Comment by jokva** [comment]
The feature required to support this is (briefly) described in, and covered by, #295 

I'll close this and consider it resolved. Support for out-of-order traces might be implemented in the future.
