### ISSUE TITLE
Planned features for 1.7

### ISSUE THREAD

**Issue by jokva** [Statoil/segyio#269]
This is mostly a note to myself to keep track of planned features for 1.7:

- #288 Seismic Unix file support
- #286 ~Python 3.7 support~
- #283 ~Refactor `text` and `attributes`~
- #282 ~Fix some old cmake cruft, streamline and simplify especially the shared/static notion and cmake-config targets.~
- Sorting when creating files should default to inline
- `from_array` or similar that would take a 2/3D array and create a SEG-Y with defaulted headers.

And, possibly:

- A public interpret method that allows forcing a volume on a file segyio can not infer
- A fallback mode in python (for starters) that interprets a volume with out-of-order traces.

**Comment by lixiandea** [comment]
Does this version have Chinese support for the Windows platform?

**Comment by jokva** [comment]
Definitely. There might also be a 1.6.x release with UTF-8 support on Windows.

**Comment by jokva** [comment]
Refactor text and attributes #283

**Comment by jokva** [comment]
~Fix some old cmake cruft, streamline and simplify especially the shared/static notion and cmake-config targets.~ #282

**Comment by jokva** [comment]
~Python 3.7 support~ #286

**Comment by jokva** [comment]
https://github.com/Statoil/segyio/releases/tag/1.7.0

We've just released 1.7.0. We didn't get all planned features in, because they turned out to be a lot more work than first anticipated, and doing them right requires some work on our test suite in particular.

Since we believe in releasing often, the current state of things is recorded and released instead. The big highlight is probably Python 3.7 support, which I know some people have been waiting for.

We hope that 1.8 will follow soon, and includes what didn't get into 1.7.0, and maybe other goodies.
