### ISSUE TITLE
Failed to install on Travis-CI

### ISSUE THREAD

**Issue by whimian** [Statoil/segyio#270]
pip install failed on Travis-CI returning "Failed Building wheel for segyio"

![screencapture-travis-ci-org](https://user-images.githubusercontent.com/3821278/44034409-9cb40bee-9f3f-11e8-850e-ecd1c166d7ab.png)

**Comment by jokva** [comment]
You're downloading the segyio source code, instead of a pre-built binary package. My guess is that your pip version is too old, and the wheel package isn't selected. What's your pip version, and can you upgrade it?

**Comment by whimian** [comment]
@jokva 

I'm using conda for package management. The version of pip provided by anaconda is 10.0.1. It works well when I install segyio on my desktop.

**Comment by jokva** [comment]
Oh, it's because you use python3.7 - no packages for 3.7 are released yet (1.7 will be the first, probably), because travis haven't been able to build it yet.

If you downgrade to 3.6 it will work.

**Comment by whimian** [comment]
@jokva

Thank you for your help.

The problem is that I forgot to write python version explicitly in conda environment file.

**Comment by jokva** [comment]
Yeah, that happens, it's always exciting with new python versions.

1.7's planned to be released also for python 3.7 - hopefully the travis images are updated till then, if not we'll have to figure something else out.

I'm closing this issue now. I hope segyio works out for you, and please don't hesitate to open new issues.
