### ISSUE TITLE
Upgrade cmake

### ISSUE THREAD

**Issue by jokva** [Statoil/segyio#272]
So I'd love to upgrade cmake from the 2.8.12 to something newer. One of the big blockers have been building multiwheels, but it seems that it's distributed also through pypi.

https://pypi.org/project/cmake/

Using cmake 3.x provides a nice opportunity to greatly simplify parts of the makefiles, and finally get to use some nice new features.

We'll let this issue sit for a little bit. If you have any compelling reasons NOT to raise the minimum required version, please let us know and we'll hold off on the upgrade.

**Comment by jokva** [comment]
#285 upgrades cmake on the centos manylinux build. It's very likely we'll upgrade the minimum cmake version, either in 1.7 or 1.8.

**Comment by jokva** [comment]
I've experimented a bit with pip-provided cmakes in old centos environments, and this works well, so segyio will from 1.8 require a higher cmake version than 2.8.12 to build.

**Comment by yuriyi** [comment]
> 
> 
> I've experimented a bit with pip-provided cmakes in old centos environments, and this works well, so segyio will from 1.8 require a higher cmake version than 2.8.12 to build.

Please update the build info in Readme, it has the old CMake version mentioned.
