### ISSUE TITLE
Method to (re)interpret structure on top of an open file

### ISSUE THREAD

**Issue by jokva** [Statoil/segyio#294]
`f.interpret` should take a set of structure-defining parameters, and populate internal structures such as inlines, crosslines, sorting etc. to enforce a known structure that isn't properly backed by headers, or add structure where there is none.

This can be both an escape hatch and a useful tool for creative interpretation of volumes.

**Comment by jokva** [comment]
#311 does most of this, but lacks for the new `su.open` and the `create` function.

**Comment by ErlendHaa** [comment]
As `interpret` is called from `infer_geometry`, #311 does in fact support `su.open` as well. I will make a new PR where `create` uses `interpret`

**Comment by jokva** [comment]
Mea culpa. Just create then.
