### ISSUE TITLE
segyio-crop might be broken

### ISSUE THREAD

**Issue by jokva** [Statoil/segyio#301]
Inspecting a few files run with segyio-crop demonstrated a file of correct number-of-traces, but with always-increasing crossline value (which seem add up to the original volume). This probably means that segyio-crop is broken, and does not produce the correct output.

This needs some verification and reproducing, and a bug squash. If anything, it needs to be verified that segyio-crop behaves as expected.

**Comment by stevejpurves** [comment]
Are there any docs on segyio-crop? i can't see any. I see it's an executable, is it exposed via the python interface yet? (again can't see it)

**Comment by jokva** [comment]
No, it's just a regular unix C program. There's a manual page `man segyio-crop` and a help text, but crop as-is is not exposed through the python interface. It's rather easy to build your own custom crop if you want that from python, but there aren't that many compelling reasons to build it into the lib. We're obviously open for counter-arguments there.

What you _can_ do is call the `segyio-crop` program through `subprocess` or something, if you really want to.

**Comment by jokva** [comment]
For what it's worth, we audited it and found the behaviour consistent, so alarm over I guess.
