### ISSUE TITLE
Loading a segy-file that is not formed as a cube

### ISSUE THREAD

**Issue by mikaelKvalvaer** [Statoil/segyio#303]
I am trying to open up a segy file that is not cube-formed, but rather is formed like a cube with thinning edges. To my understanding, `segyio` expects the segy-file to be cube-shaped. This is usually the case, but I am working with as segy-file that is not like that. See picture below. It shows how a time-slice of the dataset looks like.

![segy_shape](https://user-images.githubusercontent.com/9867901/46609777-35a5c280-cb09-11e8-8947-1079cc21bbd5.png)

When loading, it crashed in `open.py` on line 34 (`if numpy.unique(f.xlines).size != f.xlines.size`). That was quite surprising because I wouldn't expect a non-cubical geometry generate duplicate cross-lines. After skimming through issues, I noticed the assumption that `len(inlines) * len(crosslines) == len(src.trace)` must hold (as I found in this [issue](https://github.com/Statoil/segyio/issues/267#issuecomment-406345745)). So I think that is the _actual_ reason why `segyio.open` crashes. Indeed, if I do `len(inlines) * len(crosslines) / len(src.trace)` I get about 1.05, which indicates that approx 5% of traces are missing to create a cube, which seem plausible by looking at the picture.

My question is: Have you experienced this before, and if so, what can be done with it? One solution might be to crop (using `applications/segyio-crop`), but that would cause a lot of data to be lost in the cropping process. Another might be to create a filled cube with some default value (e.g. `np.nan`) for the regions that are required to generate a cube but that is not filled by the traces in the segy-file. (The ["from-array" helper](https://github.com/Statoil/segyio/issues/293) might be useful here). What might be the easiest way to do the latter? Or any other suggestions?

I am using segyio 1.7.0

**Comment by jokva** [comment]
Hi, thanks for a detailed report.

You're right that non-cube files crash, because a lot of features of segyio work on logical volumes. However, segyio fully supports opening non-cube files, you just need to explicitly ask for it.

There are two ways:

1. `segyio.open(..., strict = False)` which will, if possible, establishes volume features _if possible_, and if not falls back to trace-only.
2. `segyio.open(..., ignore_geometry = True)` which makes open not even try to determine in/crossline layout.

In either case, you can access `f.trace`, `f.header`, and `f.attributes`, because all other cases will, as you demonstrate, be somewhat non-sensical. At that point, dealing with partial cubes is left to the user.

What the best course of action is depends on what you want to accomplish. Do you want to treat this as a cube proper?

**Comment by mikaelKvalvaer** [comment]
Hello, and thank you for an instructive reply. Sorry for the late response.

I was able to recreate the cube (or actually, parts of the cube because of memory limitations) by using `segyio.open(..., ignore_geometry=True)`. and using the trace and header attributes. 

Doing something along these lines worked for me:
```
f = segyio.open('mysegyfile.segy', ignore_geometry=True)

# example geometry, extract a partial cube if the segy file is too large to handle in memory
inline_lower, inline_upper = 50, 70  # extract only inlines [50, 70)
dim_inlines, dim_crosslines, dim_Z = 100, 100, 100

D = np.ones((dim_inlines, dim_crosslines, dim_Z)) * np.nan  # np.nan indicates no trace found
for trace, header in zip(f.trace, f.header):
    if not (inline_lower <= trace[189] < inline_upper): continue  # out of bounds

    inline_idx = trace[189] - inline_offset  # if all inlines start at 50, subtract 50
    crossline_idx = trace[193] - crossline_offset  # same for crossline
    D[inline_idx, crossline_idx] = trace
````

From the parial cube `D` (with possibly missing traces), I can play around however I desire.

Many thanks for the input!

**Comment by jokva** [comment]
> I was able to recreate the cube (or actually, parts of the cube because of memory limitations) by using segyio.open(..., ignore_geometry=True). and using the trace and header attributes.

I'm sorry, memory limitations? How big is this cube? `segyio` tries to keep as reasonably little in memory as possible (unless explicitly asked otherwise) in order to support massive files, does this not work?

Glad you worked it out!

**Comment by mikaelKvalvaer** [comment]
Yes, to clarify -- memory limitations on the variable `D` that holds a small part of the cube. :)

Actually opening the segy-file (`segyio.open`) doesn't pose any memory constraints. But doing `f.trace[:]` will load the entire file in memory. So the variable `D` will only hold a few inlines at a time.

**Comment by jokva** [comment]
Actually, doing `for f in f.trace[:]` shouldn't load the entire file in memory, it should `yield` one trace at the time. Of course, if you copy that into memory then you're effectively reading the full file into memory as well, but that's an explicit operation.

**Comment by Bomb281993** [comment]
Hi @jokva , I am not able to open a segy file by using segyio.
It is giving me an error Trace count inconsistent with file size, trace lengths possibly of non uniform in segyio.
Please help.

**Comment by jokva** [comment]
Hi,

If you get that error then it means that your file is most likely corrupted. Segyio assumes that all traces are of equal length, even though the standard permits non-uniform length (the trace length then must be properly recorded in the trace header).

If you can inspect the global binary header or the textual header for clues, maybe you can figure out if the trace length (sample-count and data format) is surprising or wrong.

**Comment by Bomb281993** [comment]
Hi @jokva ,

While parsing a segyfile with segyio, i could see that while reading the segyfile for the first time it is giving valid data but for all the trace headers,but if i read the same file again from the same server(Redhat 7) it is giving me all values as 0 for the Trace header and the trace data.
Please help if you have seen such a scenario before.

**Comment by jokva** [comment]
I have not. How, exactly, do you read? Verbatim code would be best.
