### ISSUE TITLE
Depth Slice read corrupted after version 1.5.3

### ISSUE THREAD

**Issue by doiko** [Statoil/segyio#308]
There is a problem with depth_slice read after version 1.5.3.
If we read the a  segyfile using depth_slice[index] in version 1.5.3 depth slice data are correct from 1.6.0 and above depth slice data are corrupted.

Using python 3.6

**Comment by jokva** [comment]
Hi doiko,

What do you mean when you say corrupted? We fixed an issue with depth slices the other day #307, which is likely to be what you experience. We had a hole in our test suite, and this error slipped through (and was not really well thought-through to begin with).

Hopefully it should be ok in 1.7.1, which we'll release very soon.

**Comment by doiko** [comment]
Hi @jokva,
You are correct in 1.7.1 works at it should be.
Please close thread.

**Comment by jokva** [comment]
Will do, thanks for the report!
