### ISSUE TITLE
unable to find sorting

### ISSUE THREAD

**Issue by cui-xiaoang96** [Statoil/segyio#322]
i have read https://github.com/Statoil/segyio/issues/309,but my segy file have its inline and crossline ,and i can read the segy file from my notebook,but i dont do it with my desktop.
![default](https://user-images.githubusercontent.com/41711907/48308377-184b9480-e59e-11e8-8a88-5db757af7b41.png)
thanks for your help

**Comment by cui-xiaoang96** [comment]
i have soloved it ,you can conenct to https://pypi.org/project/SegyIO/1.6.0/,and uninstall your segyio1.7.0,and install segyio1.6.0 
if you have others questions please tell me in this Isssues.
good luck for you

**Comment by jokva** [comment]
Hi,

If downgrading to 1.6.0 solved it, it's likely it was never properly sorted - a bug was fixed for 1.7.0 that fixed sorting detection and fixed cases where a file was _detected_ as sorted, when in fact there was no structure.

Do you mind printing the output of `f.attributes(segyio.su.iline)[:]` and `f.attributes(segyio.su.xline)[:]`?

**Comment by cui-xiaoang96** [comment]
> 
> 
> Hi,
> 
> If downgrading to 1.6.0 solved it, it's likely it was never properly sorted - a bug was fixed for 1.7.0 that fixed sorting detection and fixed cases where a file was _detected_ as sorted, when in fact there was no structure.
> 
> Do you mind printing the output of `f.attributes(segyio.su.iline)[:]` and `f.attributes(segyio.su.xline)[:]`?

hi ,i have install segyio1.6.0.and i think it's a bug. 
![default](https://user-images.githubusercontent.com/41711907/48321388-08df5080-e65d-11e8-87e7-5fbf058ccc30.png)
in tnis figure ,il = f.attributes(segyio.su.iline)[:],output.inl_start and output.inl_end are from my segy file with using segyio1.6.0
i'm china ,so i will reply you in your night ,good night,bro!

**Comment by cui-xiaoang96** [comment]
il's elements are all zero.

**Comment by jokva** [comment]
Ok. So let's figure out _why_ this fails then.

Please run this:

```
with segyio.open(segy_file_1, ignore_geometry = True) as f:
    print(f.attributes(5)[:])
    print(f.attributes(21)[:])
    print(f.attributes(37)[:])
```

and post the output.

**Comment by cui-xiaoang96** [comment]
![default](https://user-images.githubusercontent.com/41711907/48551959-f6da0800-e911-11e8-89f8-f5b2f2387ebc.png)
hi ，i dont know f.attrabute(5)[:] & f.attrabute(37)[:] that means what is it.
and i want to know that how to get my iline and xline numbers.if possible ,can you tell me that x is traceheader number in the f.attrabute(x)[:] .thanks!

**Comment by jokva** [comment]
5 and 21 are common header word offsets for in/crossline numbers (although they're *supposed* to be trace-in-file and cdp).

From your print there it looks very much like your file is sorted and is a proper volume. If you open with `segyio.open(segy_file_1, iline = 5, xline = 21)`, geometry should be restored, and in/crossline addressing should work as expected.

**Comment by cui-xiaoang96** [comment]
thank for you help.
first,your advice is not working .
![default](https://user-images.githubusercontent.com/41711907/48553654-20496280-e917-11e8-8731-fa67273b9f36.png)
second,when i change 'print(f.attributes(5)[:])' to 'print(f.attributes(9)[:])' ,i get my iline numbers as 2135 2136 ...... 2214
![default](https://user-images.githubusercontent.com/41711907/48553741-60104a00-e917-11e8-92c1-62071f5b41df.png)
third ,when i change 'with segyio.open(segy_file_1, ignore_geometry = True) as f:' to 'with segyio.open(segy_file_1, iline = 9, xline = 21) as f:' ,the python will tell me 'unable to find sorting'.
it's so sad.
![default](https://user-images.githubusercontent.com/41711907/48553899-e036af80-e917-11e8-8aff-81c9c609a7af.png)

**Comment by jokva** [comment]
You're right - assuming the pattern holds, and is consistent, it looks like your line numbers are _descending_. There's an assumption that sorted volumes have _ascending_ line-numbers, so while it's still probably a volume, segyio doesn't realise it.

**Comment by jokva** [comment]
Ok, so before we do anything more, I think it's time to check your text header for clues.

If you run `print(f.text[0])` you could maybe get some hints as to which words are used for header fields. If it's still 5 and 21, we can consider detecting descending line numbers as sorted too.

**Comment by cui-xiaoang96** [comment]
yes，my inline numbers is descending,and i'm vary greatful for your  warnheart.best wish for you!!!

**Comment by cui-xiaoang96** [comment]
i think it is detailed.and my iline number is descending as you can look
![default](https://user-images.githubusercontent.com/41711907/48555070-1164af00-e91b-11e8-9a1e-4964b50c3262.png)

**Comment by jokva** [comment]
Yeah, that seems consistent with what you see in the headers - inlines are at 9, and crosslines at 21, so the challenge here is considering descending-traces as sorted.

**Comment by jokva** [comment]
Thank you for the report and file information! Hopefully in the not-so-distant future, segyio will detect it as sorted without any more input.

I'll close this issue now, hopefully accessing it in an unsorted fashion (`f.trace` and friends) is sufficient for you for now.

**Comment by Ajioz** [comment]
> with segyio.open(segy_file_1, ignore_geometry = True) as f:
>     print(f.attributes(5)[:])
>     print(f.attributes(21)[:])
>     print(f.attributes(37)[:])

From the above code, based on my file, here is what I got:
[    1     2     3 ... 88619 88620 88621]
[1480 1481 1482 ... 1698 1699 1700]
[0 0 0 ... 0 0 0]
