### ISSUE TITLE
is setting spec.samples alone sufficient to set the trace start time?

### ISSUE THREAD

**Issue by stevejpurves** [Statoil/segyio#327]
I have some code where I am resampling a file along the trace direction to create a longer trace.

I am attempting to set the sample range to [1000,4000] which i had expected the following code to do, however on opening the resulting file either in segyio or ODT, the sample range of the file is [0,3000]

```
with segyio.open(ORIG_CUBE, 'r+') as f:
    spec = segyio.tools.metadata(f)
    spec.samples = list(range(1000, 4004, RATE))
    spec.ilines = f.ilines
    spec.xlines = f.xlines
    
    with segyio.create(TRACE_EXTENDED_CUBE, spec) as dst:
        dst.text[0] = f.text[0]
        
        dst.bin = f.bin
        dst.bin = {
            segyio.BinField.Samples: len(dst.samples),
            segyio.BinField.Interval: RATE*1000
        }

        dst.header = f.header
        dst.header = {
            segyio.TraceField.TRACE_SAMPLE_COUNT: len(dst.samples),
            segyio.TraceField.TRACE_SAMPLE_INTERVAL: RATE*1000
        }                

        for n, trace in enumerate(f.trace):
            dst.trace[n] = np.interp(dst.samples, f.samples, trace)
```

version 1.7.0

**Comment by jokva** [comment]
Hi,

Thanks for the report! This is actually an oversight - the samples array is never inspected for delay-recording-time, which it should be.

It's a quick fix and will surely make it into 1.8.0, but in the mean time, you can get the behaviour you want by after create calling `f.bin.update(delrt = 1000)`
