### ISSUE TITLE
how to get data.cube?

### ISSUE THREAD

**Issue by data-inversion** [Statoil/segyio#335]
hello,l am a  student in chinese. l want to get the seiemic data  in python.  
l can operate segyio.open ,and  l indicate iline and xline is 9,21.
my question is that l want to get the total seiemic data ,not the some iline or xline
![image](https://user-images.githubusercontent.com/45504619/49324099-47807080-f562-11e8-88b4-e1c03cc9d5d6.png)

**Comment by jokva** [comment]
The easiest way is to use the `cube` function from tools:

https://segyio.readthedocs.io/en/latest/segyio.html#segyio.tools.cube

**Comment by data-inversion** [comment]
OK ,l know the method what you provide,but it is not work .l think problem is header of my seismic data.
although l indicate iline and xline is 9,21.
![image](https://user-images.githubusercontent.com/45504619/49335097-4febb080-f621-11e8-9f2a-852681c05a30.png)
l wish you can provide standard segy header format .beacuse different  countries use different header format
thank very much

**Comment by jokva** [comment]
I consider this resolved now. Please re-open this issue, or create a new one, if opening as sorted with `iline = 9, xline = 21` doesn't work for you.

**Comment by data-inversion** [comment]
thank  very much. l change the binary header key in my seismic data.l can get seismic data by cube methon.
