### ISSUE TITLE
strict vs. ignore_geometry for open()

### ISSUE THREAD

**Issue by krzysztof-slowinski** [Statoil/segyio#342]
Are `strict` and `ignore_geometry` parameters that can be passed to `open` equivalent? Meaning that if `strict == False` it means exactly the same as `ignore_geometry == True`? What is the priority: what if both of them are set at the same time?

**Comment by jokva** [comment]
No.

`strict = False` means that if no geometry can be determined, it falls back to opening unstructured. If `ignore_geometry = True` then segyio won't even attempt to determine geometry in the first place.

`ignore_geometry` takes preference, if it is set then strictness is nonsensical.

**Comment by krzysztof-slowinski** [comment]
So if I set `strict == True` (default) and `ignore_geometry == True` there are some other underlying processing except building the geometry that are done using `strict`?

**Comment by jokva** [comment]
Yes, segyio pretty much skips the part where it reads header to determine in/crosslines and gives you a file handle to work with.

**Comment by jokva** [comment]
This seems resolved to me - please reopen if anything is still unclear.
