### ISSUE TITLE
Writing time volume

### ISSUE THREAD

**Issue by ccamos** [Statoil/segyio#349]
I'm attempting to create a "time" 3D volume by simply overwriting the amplitude values with time values. I had planned on doing this by multiplying each sample number along a trace by the sample interval (i*375). I'm quite new to Python/programming, and can't seem to get around this error message (below). I'm looking for input as to troubleshooting this error message, or even a different method within segyio to create this "time" cube. Any help would be greatly appreciated.

>>> import numpy as np
>>> import segyio
>>> from shutil import copyfile
>>> SEGYin=("C:\\Users\\User\\Desktop\\Loss_Tangent\\rms_obs_wide_band_mig_slab.sgy")
>>> SEGout=("C:\\Users\\User\\Desktop\\Loss_Tangent\\time_vol.sgy")
>>> copyfile(SEGYin, SEGYout)
'C:\\Users\\User\\Desktop\\Loss_Tangent\\time_vol.sgy'
>>> with segyio.open(SEGYout,"r+") as src:
	for i, tr in enumerate(src.trace):
		tr = i*375
		src.trace[i]=tr

		
Traceback (most recent call last):
  File "<pyshell#69>", line 4, in <module>
    src.trace[i]=tr
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\segyio\trace.py", line 236, in __setitem__
    self.filehandle.puttr(self.wrapindex(i), xs)
ValueError: trace too short: expected 4276 bytes, got 4

**Comment by ccamos** [comment]
And FYI wrapping the [i] in brackets for use in the expression gives the following error:

>>> with segyio.open(SEGYout,"r+") as src:
	for i, tr in enumerate(src.trace):
		tr = [i]*375
		src.trace[i]=tr

		

Warning (from warnings module):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\segyio\utils.py", line 9
    warnings.warn(msg.format(type(x), np.ndarray), RuntimeWarning)
RuntimeWarning: Implicit conversion from <class 'list'> to <class 'numpy.ndarray'> (performance)
Traceback (most recent call last):
  File "<pyshell#79>", line 4, in <module>
    src.trace[i]=tr
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\segyio\trace.py", line 236, in __setitem__
    self.filehandle.puttr(self.wrapindex(i), xs)
ValueError: trace too short: expected 4276 bytes, got 1500

**Comment by jokva** [comment]
Please wrap code blocks in triple backticks (```) to get proper code formatting, right now your examples are fairly difficult to follow.

To your problem - your `tr` variable gets overwritten by the integer `i * 375` that you compute in every iteration. segyio expect the right-hand-side of the trace operation to be a compatible array.

If you want to write a transformation of the the sample interval along the trace, it's a fairly simple program:

```with segyio.open(out, 'r+') as f:
    for _ in range(len(f.trace)):
        f.trace[i] = f.samples * 375
```

`f.trace[i] =` introduces trace writing, and `f.samples * 375` will give you your time values, and be of the right dimensions. You don't actually care about the trace number, nor the trace context, so we just ignore that.

**Comment by ccamos** [comment]
Thanks for your response, and the heads-up on proper formatting.

I ran the code you suggested, however I received the error message ```RuntimeWarning: Implicit conversion from float64 to float32 (narrowing)```.  When I try to run the code again, I now get the following error (this is in a new session from my previous attempt, starting over from the beginning):

```
with segyio.open(SEGYout, "r+") as time:
	for _ in range(len(time.trace)):
		time.trace[i]=time.samples*375

		
Traceback (most recent call last):
  File "<pyshell#7>", line 3, in <module>
    time.trace[i]=time.samples*375
NameError: name 'i' is not defined
```

Any thoughts on what I'm missing here?

**Comment by jokva** [comment]
Ah yes, my bad, don't write messages when tired.

You use the trace number to identify the trace to write. Replace `for _ in range(len(time.trace)):` with `for i in range(len(time.trace)):` and you should be fine.

**Comment by ccamos** [comment]
That makes sense.  When I run this I get the error message below, but when I check the resulting trace values against my original volume they appear sensible. From your experience, is this an error message that needs to be addressed? 

```
with segyio.open(SEGYout, "r+") as time:
	for i in range(len(time.trace)):
		time.trace[i]=time.samples*375

		

Warning (from warnings module):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\segyio\utils.py", line 23
    warnings.warn(msg.format(x.dtype, dtype), RuntimeWarning)
RuntimeWarning: Implicit conversion from float64 to float32 (narrowing)
>>> with segyio.open(SEGYout, "r") as time:
	print(time.trace[10])

	
[0.0000000e+00 1.4062500e+02 2.8125000e+02 ... 1.4990625e+05 1.5004688e+05
 1.5018750e+05]
>>> with segyio.open(SEGYin, "r") as src:
	print(src.trace[10])

	
[0.01434717 0.01252531 0.01115891 ... 0.01096432 0.0123069  0.01409699]
```

Thanks again for your help

**Comment by jokva** [comment]
I wouldn't worry too much about it, it just means segyio implicitly converts from float64 to float32. It's hardly noticeable speed-wise (it shouldn't be anyway), and you're nowhere near dangerous rounding errors.

**Comment by ccamos** [comment]
Does ```f.samples``` call the sample number, i.e. [0, 1, 2,..., n]? If so, I'm having trouble understanding the output listed below. I've updated the expression I'm using to reflect correct units and time lag of my data (starting time is 999.75, sample interval is 0.375). When I check the output trace, the first value is what I would expect (999.75) however the values do not increase by the sample interval as I would expect. If ```f.samples``` called increasing integers, then the second value in my output array should be ```999.75 + ([1] * 0.375) = 1000.125```, instead my output values appear to be increasing at a rate of 0.1406

```
with segyio.open(SEGYout, "r+") as time:
	for i in range(len(time.trace)):
		time.trace[i] = 999.75 + (time.samples * 0.375)

		
with segyio.open(SEGYout, "r") as time:
	print(time.trace[3])
	print(time.trace[218])

	
[ 999.75     999.8906  1000.03125 ... 1149.6562  1149.7969  1149.9375 ]
[ 999.75     999.8906  1000.03125 ... 1149.6562  1149.7969  1149.9375 ]
```

I've made a few different attempts to include ```f.samples[i]```, all of which resulted in a ValueError

**Comment by ccamos** [comment]
I sorted out that ```f.samples``` equals the sample number times the sample rate, and produced my needed output by:

```
>>> with segyio.open(SEGYout, "r+") as time:
	for i in range(len(time.trace)):
		time.trace[i] = 999.75 + time.samples

		
>>> with segyio.open(SEGYout, "r") as time:
	print(time.trace[3])
	print(time.trace[457])

	
[ 999.75  1000.125 1000.5   ... 1399.5   1399.875 1400.25 ]
[ 999.75  1000.125 1000.5   ... 1399.5   1399.875 1400.25 ]
```

Thanks again for your help, and for everyone maintaining this useful piece of software
