### ISSUE TITLE
Python: Line/offset subindexing; behaviour

### ISSUE THREAD

**Issue by jokva** [Statoil/SegyIO#52]
I'm working on the pre-stack support in python, and I wanted to put the following up for discussion and   consideration.

Consider the file 50x40 file **F** with samples = 20 that has 10 offsets and the following code:

```
f.iline[10, 3] 
```

This would give us a 40x20-element ndarray, i.e. the line at offset 3. Now consider:

```
f.iline[1:10, 3]
```

This would return a *generator* that yields a 40x20-element ndarray (lines 1 through 9 at offset 3).

So far so good. However, what should

```
f.iline[1:10, 3:5]
f.iline[10, 3:5]
```

return? We have a few options:

* Both yield a generator that would yield 18 (9*2) 40x20 ndarrays, i.e. the first 9 lines would be offset 3, the next nine lines would be offset 4.
* The former returns a generator that yields 2 9x40x20 ndarrays, the latter returns a generator that yields 2 40x20 ndarrays
* The former returns a generator that yields 9 2x40x20 ndarrays (i.e. offset x iline x xline), the latter returns a 2x40x20 ndarray
* Any more?

Discussion & opinions welcome.

**Comment by jepebe** [comment]
For 

`f.iline[1:10, 3:5]`

I think I would expect a generator that produces:

**Comment by jokva** [comment]
Right, so the inverse of the first bullet point really.

**Comment by jepebe** [comment]
However, we will also need something like:

`f.iline.gather[7, :]`

That will return a 2D slice that is (400, 20). All offsets for inline 7.

**Comment by jokva** [comment]
Won't that feel maybe too inconsistent? It's obviously not a problem supporting it, but all other python slice configurations of `[]` would yield a generator.

**Comment by jokva** [comment]
I'll elaborate a bit. Currently we have:

| Operation | Result |
|--------------|:---------|
| `line[n]`     | ndarray |
| `line[n, k]` | ndarray |
| `line[n:m]`  | gen[ndarray] |
| `line[n:m, k] | gen[ndarray] |
| `line[n:m, k:l] | gen[ndarray] |


... and I just realise I'm an idiot and we're talking about a gather submode with a different, raw-like indexing scheme. Please carry on.

**Comment by jokva** [comment]
https://github.com/Statoil/SegyIO/pull/58 solves this.
